apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: ebook-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
        version: v1
    spec:
      containers:
      - name: book-service
        image: book-service:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: ENV
          value: "kubernetes"