apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: ebook-microservice
spec:
  selector:
    app: book-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  type: ClusterIP