spring:
  output.ansi.enabled: ALWAYS
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/user-service
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  port: 8080

springdoc:
  show-actuator: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html